name: Meta Security Pipeline

on:
  workflow_dispatch:

jobs:
  #trigger-sca:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Trigger SCA (Snyk)
  #      uses: peter-evans/repository-dispatch@v3
  #      with:
  #        token: ${{ secrets.REPO_ACCESS_TOKEN }}
  #        event-type: sca-snyk
  #
  #trigger-sast:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Trigger SAST (Semgrep)
  #      uses: peter-evans/repository-dispatch@v3
  #      with:
  #        token: ${{ secrets.REPO_ACCESS_TOKEN }}
  #        event-type: sast-semgrep

  trigger-dast:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DAST (OWASP ZAP)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: dast-zap

  #trigger-iac:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Trigger IaC (Trivy)
  #      uses: peter-evans/repository-dispatch@v3
  #      with:
  #        token: ${{ secrets.REPO_ACCESS_TOKEN }}
  #        event-type: iac-trivy
