name: DAST with OWASP ZAP

on:
  repository_dispatch:
    types: [dast-zap]

permissions:
  contents: write
  issues: write
  security-events: write

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          cni: bridge
          container-runtime: containerd
          cpus: 2
          memory: 4096m
          start-args: '--wait=apiserver'

      - name: Set up the microservice
        run: |
          eval $(minikube -p minikube docker-env)
          export DOCKER_BUILDKIT=0
          docker build -t microservizio-js:v1 .
          kubectl apply -f microservizio-js-deployment.yaml
          kubectl rollout status deployment/microservizio-js --timeout=120s
          for i in {1..30}; do
            if kubectl get svc microservizio-js-service; then
              echo "Service is ready."
              break
            fi
            echo "Waiting for service..."
            sleep 5
          done

      - name: Get Service URL
        id: service-url
        run: |
          echo "SERVICE_URL=$(minikube service microservizio-js-service --url)" >> $GITHUB_ENV

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ env.SERVICE_URL }}
          cmd_options: '-a'

      - name: Cleanup
        if: always()
        run: |
          kubectl delete -f microservizio-js-deployment.yaml
