name: DAST with OWASP ZAP

on:
  repository_dispatch:
    types: [dast-zap]

permissions:
  contents: write
  issues: write
  security-events: write

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and run app
        run: |
          docker build -t microservizio-js:v1 .
          docker run -d -p 3000:3000 --name app microservizio-js:v1
          sleep 10

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000'
          artifact_name: zap_reports
          cmd_options: '-a'

      - name: Stop app container
        if: always()
        run: docker stop app
