name: DAST with OWASP ZAP

on:
  repository_dispatch:
    types: [dast-zap]

permissions:
  security-events: write

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and run app
        run: |
          docker build -t microservizio-js:v1 .
          docker run -d -p 3000:3000 --name app microservizio-js:v1
          sleep 10

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          format: 'sarif'
          output: 'zap.sarif'

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: zap.sarif

      - name: Stop app container
        if: always()
        run: docker stop app