name: Static Application Security Testing with Semgrep

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  semgrep-scan:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Semgrep Scan
        run: |
          semgrep scan \
            --config=p/javascript \
            --config=p/nodejs \
            --config=p/express \
            --config=p/owasp-top-ten \
            --output=semgrep-results.sarif \
            --sarif
            
      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
          wait-for-processing: true
          
      - name: Upload scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep-results.sarif
