name: SAST with Semgrep

on:
  repository_dispatch:
    types: [sast-semgrep]

permissions:
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep SAST
        run: |
          semgrep scan --config=p/owasp-top-ten --config=p/javascript --output=semgrep.sarif --sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif